version: "3.8"

services:
  home:
    build: ./home
    ports:
      - "3000:3000"
    networks:
      - kilim-network

  cart:
    build: ./cart
    ports:
      - "3001:3001"
    networks:
      - kilim-network

networks:
  kilim-network:
    driver: bridge
